### ISSUE TITLE
Дальнейшая разработка модуля

### ISSUE THREAD

**Issue by spigell** [melezhik/sparrowdo-nginx#3]
Здравствуйте. Вы планируете дальше разрабатывать и поддерживать этот модуль? Он бы многим пригодился в будущем. 
Например, было бы неплохо, если в параметрах можно было бы указывать путь до шаблонов, хостнейм, порт, адрес.

**Comment by melezhik** [comment]
Приветствую. Все зависит от спроса.  Пока я написал данной модуль скорее в показательных целях, но если есть желание что-то добавить ... можно будет обсудить ... Но мне бы не хотелось делать модуль через чур сложным и гибким. 

Вы напишите сюда конкретно что бы вы хотели - и я подумаю ...

**Comment by melezhik** [comment]
> указывать путь до шаблонов, хостнейм, порт, адрес.

Видимо вот это?

**Comment by spigell** [comment]
Я хотел бы использовать этот модуль примерно так:
```
module_run 'Nginx', %(
  state => 'enabled'  # Это значит, что nginx поставится и добавится в автозагрузку
);  

module_run 'Nginx::resource', %(
  template => '/path/to/file',
  conf => '/path/to/file',
  port => 80
  ip => 127.0.0.1
  hostname => 'example.com'
);
```
То есть хотелось бы разделить модуль, чтобы он не всегда пытался ставить nginx при изменении/добавлении конфига. 
Как вы считаете?

**Comment by melezhik** [comment]
Да, я вас понял. В принципе идея нормальная, в других инструментах (chef, ansibe) есть похожие решения. Но, я не уверен, правда, что смогу активно развивать этот модуль в ближайшее время, т.к. есть много других задач. Давайте я подумаю.

**Comment by spigell** [comment]
Понимаю. Давайте в таком случае все же отложим этот модуль на более лучшее время.
